services:
    lordbeaver.chevereto.listener:
        class: lordbeaver\chevereto\event\listener
        arguments:
            - @cache.driver
            - @config
            - @log
            - @user
        tags:
            - { name: event.listener }