services:
    lordbeaver.chevereto.listener:
        class: lordbeaver\chevereto\event\listener
        arguments:
            - @cache.driver
            - @config
            - @language
            - @request
            - @template
        tags:
            - { name: event.listener }